server:
  port: 8081
  use-forward-headers: true
spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      username: mongoadmin
      password: secret
      authentication-database: admin
eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:9001/eureka/