server:
  port: 8081
  use-forward-headers: true
spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      username: mongoadmin
      password: secret
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9103/uaa/token_keys
eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:9001/eureka/
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG